---
- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    image: ami-db710fa3
    keypair: nathan_try
    region: us-west-2
    count: 1
    #vars_files:
    #- secrets.yml
  tasks:
    - name: launch ec2 web 
      ec2:
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: "{{count}}"
        instance_tags:
          Name: Nathan_Web
        #user_data: "{{ Jenny_apache }}"
      register: web
    - name: add it to hosts file
      add_host:
        name: "{{ item.public_ip }}"
      with_items: "{{ web.instances }}"
    - name: output instance id
      debug: msg="{{item.id}}"
      with_items: "{{ web.instances }}"
    - local_action: copy content={{ item.id }} dest=./web_instance_id.txt
      with_items: "{{ web.instances }}"
    - command: "aws s3 cp ./web_instance_id.txt s3://test-nathan-5-14/ --grants full=uri=http://acs.amazonaws.com/groups/global/AllUsers"

