# - name: install terraform
#   import_playbook: install_tf.yml

- name: terraform apply
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: apply
      terraform:
        force_init: "{{ force_init }}"
        project_path: ../terraform/ # required
        backend_config:
          region: "us-east-1"
          bucket: "awx-nextlinker-cmdb"
          key: "terraform.tfstate"
        state: present # present, absent, planned
        variables:
          webserver_ip: "{{ webserver_ip }}"
          dbserver_ip: "{{ dbserver_ip }}"
          web_ami_id: "{{ apache2_ami_id }}"
          db_ami_id: "{{ mysql_server_ami_id }}"
          AWS_REGION: "{{ AWS_REGION | default('us-east-1') }}"
          availability_zone: "{{ availability_zone | default('us-east-1a') }}"
          key_name: "{{ key_name | default('nathan_east1_key') }}"