- name: terraform destroy
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    # - name: terraform init
    #   command:
    #     cmd: terraform init
    #     chdir: ../terraform/
    - name: destroy
      terraform:
        project_path: ../terraform/
        backend_config:
          region: "us-east-1"
          bucket: "awx-nextlinker-cmdb"
          key: "terraform.tfstate"
        state: absent
        variables:
          webserver_ip: "{{ webserver_ip }}"
      tags:
        - destroy
